name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
    - name: Prepare SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }}  > ~/.ssh/known_hosts
    - name: Pull latest
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls muckraker/"
        echo "Successfully pulled repo"

